### get all movies with timeslot availabe
get http://localhost:8000/api/movie/retrieve 

### create movie 
POST http://localhost:8000/api/movie/create 

### retrive movies
get http://localhost:8000/api/movie/all
