### get all movies with timeslot availabe
GET http://localhost:8000/api/movie/retrieve 

### create movie 
POST http://localhost:8000/api/movie/create 

### retrive movies
GET http://localhost:8000/api/movie/all
