## get all timeslot 
GET http://localhost:8000/api/timeSlot/all
## add movie to time slot  
PATCH  http://localhost:8000/api/timeSlot/update 

## create time slot
POST http://localhost:8000/api/timeSlot/create 
## reserve time slot 
PATCH  http://localhost:8000/api/timeSlot/reserve 
## retrive one time slot 
GET http://localhost:8000/api/timeSlot/check 
